name: deployment

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

env:
  POSTGRES_HOST: postgres
  DB_NAME: startie
  DB_USERNAME: oliver
  DB_PASSWORD: oliver
  IMAGE_TAG: latest

jobs:
  server-testing:
    runs-on: ubuntu-latest
    container: node:latest
    env:
      DB_HOST: postgres
    services:
      postgres:  
        image: postgres
        env: 
          POSTGRES_DB: ${{env.TESTDB_NAME}}
          POSTGRES_USERNAME: ${{env.DB_USERNAME}}
          POSTGRES_PASSWORD: ${{env.DB_PASSWORD}}
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: Testing
        run: |
          cd backend
          yarn install
          yarn knex migrate:latest --env test
          yarn knex seed:run --env test     
          yarn jest

  server-deploy:
     if: github.ref_name == 'production'
     runs-on: ubuntu-latest
     needs: testing
     steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
       with:
        python-version: "3.6"
      - run: |
        cd backend
        pip install awscli
       with:
         command: |
           cd AI86
           git pull 
           yarn knex migrate:latest
           yarn knex seed:run 
           forever restart 0
         host: 18.136.98.33
         user: ubuntu
         key: ${{secrets.SSH_PRIVATE_KEY}}